# Generated by Django 3.1.2 on 2020-11-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense',
            field=models.BooleanField(default=False),
        ),
    ]
